# Generated by Django 5.0.2 on 2025-07-12 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('phone', models.CharField(blank=True, max_length=15, null=True, unique=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('name', models.CharField(max_length=100)),
                ('role', models.CharField(blank=True, choices=[('farmer', 'Farmer'), ('administrator', 'Administrator'), ('government_official', 'Government Official'), ('expert_advisor', 'Expert Advisor'), ('retailer', 'Retailer')], max_length=32)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='profile_images/')),
                ('state', models.CharField(blank=True, max_length=100)),
                ('district', models.CharField(blank=True, max_length=100)),
                ('village', models.CharField(blank=True, max_length=100)),
                ('preferred_language', models.CharField(blank=True, max_length=50)),
                ('type_of_farming', models.CharField(blank=True, max_length=50)),
                ('main_crops', models.CharField(blank=True, max_length=255)),
                ('farm_size', models.CharField(blank=True, max_length=50)),
                ('voice_input_access', models.BooleanField(blank=True, null=True)),
                ('receive_govt_alerts', models.BooleanField(blank=True, null=True)),
                ('expertise_area', models.CharField(blank=True, max_length=100)),
                ('experience_years', models.PositiveIntegerField(blank=True, null=True)),
                ('state_of_operation', models.CharField(blank=True, max_length=100)),
                ('languages_spoken', models.CharField(blank=True, max_length=100)),
                ('available_for_consult', models.BooleanField(blank=True, null=True)),
                ('certificates', models.FileField(blank=True, null=True, upload_to='certificates/')),
                ('designation', models.CharField(blank=True, max_length=100)),
                ('region_of_responsibility', models.CharField(blank=True, max_length=100)),
                ('access_level', models.CharField(blank=True, choices=[('full', 'Full'), ('partial', 'Partial'), ('content_only', 'Content Only')], max_length=20)),
                ('employee_id', models.CharField(blank=True, max_length=50)),
                ('admin_password', models.CharField(blank=True, max_length=128)),
                ('department_name', models.CharField(blank=True, max_length=100)),
                ('official_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('gov_designation', models.CharField(blank=True, max_length=100)),
                ('schemes_managed', models.CharField(blank=True, max_length=255)),
                ('gov_id_badge', models.FileField(blank=True, null=True, upload_to='gov_ids/')),
                ('portal_access_required', models.BooleanField(blank=True, null=True)),
                ('business_name', models.CharField(blank=True, max_length=100)),
                ('location', models.CharField(blank=True, max_length=100)),
                ('type_of_business', models.CharField(blank=True, choices=[('wholesaler', 'Wholesaler'), ('local_buyer', 'Local Buyer'), ('agri_retailer', 'Agri Retailer')], max_length=20)),
                ('interested_crops', models.CharField(blank=True, max_length=255)),
                ('license_gst_number', models.CharField(blank=True, max_length=50)),
                ('buyer_dashboard_access', models.BooleanField(blank=True, null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
