# Generated by Django 5.2.4 on 2025-08-06 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GovernmentScheme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('benefit', models.TextField()),
                ('eligibility', models.TextField()),
                ('docs', models.TextField(help_text='Required documents (comma-separated or description)')),
                ('apply_url', models.URLField()),
            ],
        ),
    ]
