# Generated by Django 5.2.4 on 2025-08-07 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmers', '0003_blog_user_saved_posts_comment_poll_choice_blog_poll_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='content',
            field=models.TextField(max_length=2000),
        ),
    ]
